@startuml
!include tema.puml
left to right direction

component "sync_api" as S
component "async_api" as A
component "KafkaPublisher" as P
component "consumer" as C
component "schemas + processing\n+ database" as N
queue "Kafka\naudit-events + DLQ" as K
database "PostgreSQL\naudit_records" as D

S -right-> N : persistir
A -right-> P : publicar
P -right-> K : ACK
K -down-> C : consumir
C -left-> N : persistir
N -right-> D : SQL
@enduml
