@startuml
!include tema.puml
left to right direction
skinparam nodesep 32
skinparam ranksep 60
actor "Aplicação cliente" as C
actor "Pesquisador" as P
rectangle "Implementação Java: APIs e consumidor" {
 usecase "UC01\nRegistrar sincronamente" as U1
 usecase "UC02\nAceitar assincronamente" as U2
 usecase "UC03\nConsumir e persistir" as U3
 usecase "UC04\nConsultar prontidão" as U4
 usecase "UC07\nConsultar registro por UUID" as U7
 U1 -[hidden]right- U2
 U2 -[hidden]right- U3
 U3 -[hidden]right- U7
 U7 -[hidden]right- U4
}
actor "PostgreSQL" as D <<sistema externo>>
actor "Kafka" as K <<sistema externo>>
C -- U1
C -- U2
P -- U4
P -- U7
U1 -- D
U7 -- D
U2 -- K
U3 -- K
U3 -- D
@enduml
